#!/bin/sh

SITE="site_name"
COM="flower"
MOD="flower"
PLG="flower"
GUP="system"


rm ../com_$COM.zip

# admin
rm -rf admin
mkdir admin
cp -rf /var/www/$SITE/administrator/components/com_$COM/ admin
echo "Admin copied" ;

# site
rm -rf site
mkdir site
cp -rf /var/www/$SITE/components/com_$COM/ site
echo "Site copied" ;

# library
# rm -rf admin/windwalker
# mkdir admin/windwalker
# cp -rf /var/www/$SITE/libraries/windwalker/ admin/windwalker
# rm -rf admin/windwalker/.git
# rm -f admin/windwalker/.gitignore
# echo "Lib copied" ;

# xml and install script
# cp -f /var/www/$SITE/administrator/components/com_$COM/$COM.xml .
# echo "Component XML copied" ;

# cp -f /var/www/$SITE/administrator/components/com_$COM/install.php .
# echo "Component install scrip copied" ;

# modules site
# rm -rf modules
# mkdir modules
# cp -rf /var/www/$SITE/modules/mod_$MOD/ modules/mod_$MOD
# echo "Module copied" ;

# modules admin
# rm -rf modules
# mkdir modules
# cp -rf /var/www/$SITE/administrator/modules/mod_$MOD/ modules/mod_$MOD
# echo "Module copied" ;

# plugins
# rm -rf plugins
# mkdir plugins
# cp -rf /var/www/$SITE/plugins/$GUP/$PLG/ plugins/plg_$GUP\_$PLG
# echo "Plugin copied" ;


git add .
echo "Execute git add" ;

zip -rq ../com_$COM.zip *
echo "Ziped files" ;


exit 0
